---
- name: Copy the alertmanager systemd service file
  template:
    src: alertmanager.service.j2
    dest: /lib/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify: restart alertmanager

- name: Copy the alertmanager config file
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
    validate: "{{ alertmanager_install_dir }}/amtool check-config %s"
  notify: restart alertmanager

- name: copy alertmanager template files
  copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_config_dir }}/templates/"
    force: true
    owner: "{{ alertmanager_system_user }}"
    group: "{{ alertmanager_system_group }}"
    mode: 0644
  with_fileglob: "{{ alertmanager_template_files }}"
  notify:
    - restart alertmanager
